/**
@author Ian
*/
package edu.umw.cpsc240fall2015team3.zork;
/**Displays the current numeric health of the player.
*/
class ShowHealthCommand extends Command {
/**Returns a {@link edu.umw.cpsc240fall2015team3.zork.ShowHealthCommand} generated by a player's input in the {@link edu.umw.cpsc240fall2015team3.zork.Interpreter}.
*/
    ShowHealthCommand(){}
/**
Returns a String containing the desription of the player's current Health.
*/
    public String execute(){
	//Can Edit later to check for specific levels of Health
	int health = GameState.instance().getAdventurersHealth();
	if(health > 100){return "You are beaming with energy\n";}
	if(health > 90 && health <= 100){return "You feel energetic, ready to explore\n";}
        if(health > 70 && health <= 90){return "You feel a bit tired\n";}
        if(health > 50 && health <= 70){return "You feel out of breath\n";}
        if(health > 30 && health <= 50){return "Its hard to keep a steady breathing pattern\n";}
        if(health > 20 && health <= 30){return "Most of your effort is spent trying to stay on your feet\n";}
        if(health > 10 && health <= 20){return "Your legs are twitching uncontrollably and it is hard to stay concious\n";}
        if(health > 5 && health <= 10){return "It is a battle to stay concious at this point\n";}
        if(health > 0 && health <= 5){return "You cant focus at all and feel very sleepy\n";}
	else {return "You are dead\n";}
	}
}
