/**
@author Ian
*/
package edu.umw.cpsc240fall2015team3.zork;
/**Displays the current numeric health of the player.
*/
class ShowHealthCommand extends Command {
/**Returns a {@link edu.umw.cpsc240fall2015team3.zork.ShowHealthCommand} generated by a player's input in the {@link edu.umw.cpsc240fall2015team3.zork.Interpreter}.
*/
    ShowHealthCommand(){}
/**
Returns a String containing the desription of the player's current Health.
*/
    public String execute(){}
}
