/**
@author Ian
*/
package edu.umw.cpsc240fall2015team3.zork;
/**Displays the current numeric health of the player.
*/
class ShowHealthCommand extends Command {
    private static GameState state;
/**Returns a {@link edu.umw.cpsc240fall2015team3.zork.ShowHealthCommand} generated by a player's input in the {@link edu.umw.cpsc240fall2015team3.zork.Interpreter}.
*/
    ShowHealthCommand(){}
/**
Returns a String containing the desription of the player's current Health.
*/
    public String execute(){
	//Can Edit later to check for specific levels of Health
	health = state.getAdventurersHealth();
	if(health <= 0){
	    return "You are dead";
	else {
	    return "You are alive";
	}
	}
}
